### ISSUE TITLE
Can´t use single proxy url

### ISSUE THREAD

**Issue by nikgerx** [timbru31/mms-stockshock#100]
Hey, 
I´m can´t using single proxy url. I´m getting always "Unable to visit start page...".  Is it a bug or am I dump? 
When I´m using multiple proxies, then it works but i want to use the single one ^^

![image](https://user-images.githubusercontent.com/38695265/121759019-1b2b0f00-cb24-11eb-93ea-0c03335a8173.png)

**Comment by timbru31** [comment]
Works as expected.
