### ISSUE TITLE
Unable to Parse the config file

### ISSUE THREAD

**Issue by pptothemoon** [timbru31/mms-stockshock#252]
**Describe the bug**
When I try to start the bot, it says that it is unable to parse the config file. I fileld almost everything in the stores file and renamed it so I dont know what other issue I could have!

**To Reproduce**
1. I put the files in a folder and filled in my info in stores.toml, then opened cmd and executed npm install
2. Then I executed 'npm start'
3. Everything started, but I then got the error:
2021-09-01 20:54:07 [⚡️] error: Uh oh! Unable to parse the config file!
2021-09-01 20:54:07 [⚡️] error: Expected "#", "'", "'''", "+", "-", "[", "\"", "\"\"\"",  "\n", "\r", "]", "_", "false", "true", "{", [ \t] or [0-9] but "e" found.

**Expected behavior**
I expected the cli to start the bot

**Screenshots**
![image](![Screenshot_1](https://user-images.githubusercontent.com/89939225/131729095-becd8c48-3d89-4884-8657-58b068d01943.png))

**Desktop (please complete the following information):**
- Windows 10
- Version 5.2.0
- Node.js v7.20.3
- Don't use docker atm
- Git Hash

**Additional context**
I guess the error is simple, but I don't know what to do!

**Comment by timbru31** [comment]
Your config file is invalid, nothing I can fix nor a bug
