### ISSUE TITLE
Docker Issue

### ISSUE THREAD

**Issue by sleeplezz1** [timbru31/mms-stockshock#31]
Getting this if i want to install the docker image

Sending build context to Docker daemon  545.9MB
Step 1/10 : FROM timbru31/node-chrome:alpine
alpine: Pulling from timbru31/node-chrome
no matching manifest for windows/amd64 10.0.17763 in the manifest list entries

**Comment by timbru31** [comment]
The Docker image is provided for linux/amd64 and linux/arm64 - as it's based on Alpine Linux. Therefore I won't provide a Windows based image.

There are however plenty of "fixes" for your issue, see, e.g., https://stackoverflow.com/q/48066994/1902598
