### ISSUE TITLE
Proposal for circumventing the Cloudflare Bot Detection

### ISSUE THREAD

**Issue by spyfly** [timbru31/mms-stockshock#41]
I have been experiencing the issues with the Cloudflare Bot Detection on my own stock checker aswell and I was able to resolve them by using a Firefox Headless Browser powered by https://playwright.dev.

So maybe it would be worth considering migrating from puppeteer to the more modern playwright, to resolve this issue.

If this sounds like a great idea to you, I could look into filing a PR, when I have some spare time.

**Comment by timbru31** [comment]
What's the benefit of using playwright? Puppeteer supports Firefox, too (although it's still in beta I think). With the stealth plugin (https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth) CloudFlare does not detect the headless browser. If you set the delay too low you'll run in 429 nevertheless, i.e., you will need rotating proxies at some point.

**Comment by spyfly** [comment]
> What's the benefit of using playwright? Puppeteer supports Firefox, too (although it's still in beta I think). With the stealth plugin (https://github.com/berstend/puppeteer-extra/tree/master/packages/puppeteer-extra-plugin-stealth) CloudFlare does not detect the headless browser. If you set the delay too low you'll run in 429 nevertheless, i.e., you will need rotating proxies at some point.

In this case there is no need for migrating to playwright and this issue is obsolete.
