### ISSUE TITLE
Cookie links dont‘t work

### ISSUE THREAD

**Issue by diggasbox** [timbru31/mms-stockshock#43]
Where can I find the created cookies? I used the links from the log bot nothing happened.

Tks in advance.

**Comment by timbru31** [comment]
The cookies are logged and send to Discord/Slack via the Webhook:

https://github.com/timbru31/mms-stockshock/blob/master/src/notifier.ts#L99-L125

**Comment by diggasbox** [comment]
Still doesn’t work. Created a webhook, everything appears in DC, but nothing is added to the cart, when i click on link

**Comment by timbru31** [comment]
Yes that's expected. You need to figure that our for yourself how to apply cookies.

**Comment by diggasbox** [comment]
I found out that the cookie with the name „r“ is copied and logged, but nothing happens, when i change the value of r in the browser.
