### ISSUE TITLE
Discord Webhook

### ISSUE THREAD

**Issue by diggasbox** [timbru31/mms-stockshock#45]
I pasted the DC webhook URL and got the following error in log:

 [⚡️] error: Error sending webook, error codeslack_webhook_http_error
 [⚡️] error: Discord error data, { message: 'Cannot send an empty message', code: 50006 }
 [⚡️] error: HTTP error headers, {
  date: 'Sat, 15 May 2021 18:46:58 GMT',
  'content-type': 'application/json',
  'content-length': '58',
  connection: 'close',

**Comment by timbru31** [comment]
You need to use the Slack variant: https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook
