### ISSUE TITLE
Discord Notification | MMS-Stockshock

### ISSUE THREAD

**Issue by nikgerx** [timbru31/mms-stockshock#50]
Hey,
I'm always getting this Error-Code when I'm implement the weebhook. 

![image](https://user-images.githubusercontent.com/38695265/118654856-47839200-b7e9-11eb-98cc-7cea09bc8779.png)

**Comment by timbru31** [comment]
https://github.com/timbru31/mms-stockshock/issues/45#issuecomment-841713096
