### ISSUE TITLE
'PersistedQueryNotFound'

### ISSUE THREAD

**Issue by sleeplezz1** [timbru31/mms-stockshock#55]
Getting 

`Errors: {
  errors: [ { message: 'PersistedQueryNotFound', extensions: [Object] } ]`

After entering query hash's

**Comment by timbru31** [comment]
Then the hash is wrong. They tend to change with every deployment from MM/S and potentially can be different for each store, that's why I've made them user configurable. Sadly, it's a cat and mice game.
