### ISSUE TITLE
403 code at GetSelectProduct

### ISSUE THREAD

**Issue by pvhil** [timbru31/mms-stockshock#674]
**Describe the bug**
After successfully checking the category, a 403 respond code pops up after the GetSelectProduct Query

**To Reproduce**
1. Get a correct category ID with newest sha256 hashes
2. Run the program and let it check for the category
3. A 403 pops up (cloudflare)

**Expected behavior**
After successfully getting category information, it should get product information with getselectproduct

**Desktop (please complete the following information):**
- OS: Windows 11 newest
- Node.js version 16.3.1

**Comment by timbru31** [comment]
Please try setting `cache_busting = false`.  
Otherwise use different proxies.
