### ISSUE TITLE
cart-adder.ts ; chance addToCartCooldownMap to addToBasketCooldownMap

### ISSUE THREAD

**Issue by sleeplezz1** [timbru31/mms-stockshock#68]
src/cart-adder.ts:178:42 - error TS2551: Property 'addToCartCooldownMap' does not exist on type 'CooldownManager'. Did you mean 'addToBasketCooldownMap'?

178                     this.cooldownManager.addToCartCooldownMap(product);
                                             ~~~~~~~~~~~~~~~~~~~~

  src/cooldown-manager.ts:40:5
    40     addToBasketCooldownMap(product: Product): void {
           ~~~~~~~~~~~~~~~~~~~~~~
    'addToBasketCooldownMap' is declared here.

**Comment by timbru31** [comment]
Probably your working directory is dirty, make sure to pull the latest commits and to properly clean it. There is no `cart-added.ts` file anymore as it was renamed.
