### ISSUE TITLE
dynamodb

### ISSUE THREAD

**Issue by pressplay01** [timbru31/mms-stockshock#84]
Hey,
erstmal vielen dank für deinen genialen monitor, klasse arbeit!
ich bekomme leider nur auf verrecken die dynamodb nicht angesprochen.
ich erhalte dauernd:

Unhandled Rejection reason: ValidationException: The provided key element does not match the schema

in der store_config habe ich es wie folgt eingetragen:

dynamo_db_region = "eu-central-1"
dynamo_db_table_name = "saturn"
dynamo_db_access_key = "AKIA2BCC4A3G4?????????"
dynamo_db_secret_access_key = "iKJwPfUVAMoS3lpuA8G????????????"

kannst du mir evtl einen tipp geben wo der fehler liegt?

**Comment by timbru31** [comment]
Make sure to set Primary partition key to store (String) and Primary sort key to productId (String). Cookies need to be a List, not a StringSet.
