### ISSUE TITLE
multi proxy issue 

### ISSUE THREAD

**Issue by sleeplezz1** [timbru31/mms-stockshock#86]
always getting 

`error: Uh oh! Unable to parse the config file!
 error: Expected "#", "'", "'''", "+", "-", "[", "\"", "\"\"\"", "\n", "\r", "]", "_", "false", "true", "{", [ \t] or [0-9] but "h" found.`

format of prxy_urls

proxy_urls = [http://USER:PASS@IP:PORT,http://USER:PASS@IP:PORT,http://USER:PASS@IP:PORT]

Whats wrong here ?

**Comment by timbru31** [comment]
They need to be strings.
